# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'MMPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.1'
  # Pods for MMPlayer

  target 'MMPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MMPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
